### ISSUE TITLE
NextSeq ?

### ISSUE THREAD

**Issue by colindaven** [GenomicParisCentre/aozan#2]
Hi,

could this system also work for NextSeqs or is it restricted to HiSeq ?

Thanks,
Colin

**Comment by jourdren** [comment]
Hi Colin,

You can use Aozan with almost all Illumina sequencers. We use a NextSeq sequencer in our genomics core facility and it works well. The main page of Aozan website contain the list of supported sequencers:

http://www.outils.genomique.biologie.ens.fr/aozan/

Do not hesitate to contact me if you have any question about Azoan installation.

Best regards,

Laurent.
