### ISSUE TITLE
Make underscore illegal for Sample_Name and Sample_ID?

### ISSUE THREAD

**Issue by woook** [GenomicParisCentre/aozan#6]
Hello - would you consider making underscore an illegal character for Sample_Name and Sample_ID?

This is now a reserved character for basespace (which not everyone uses of course) but Illumina are recommending against underscores. For example see https://support.illumina.com/help/BaseSpace_App_UMI_Error_Correction_OLH_1000000035906/Content/Source/Informatics/TruSight_UMI/PrepareSampleSheet_fTST_mUMI.htm

**Comment by jourdren** [comment]
Dear woook,

We plan to handle this in the next version of Aozan that will be available in one or two months.

Regards.

**Comment by woook** [comment]
Brilliant, thanks!

**Comment by jourdren** [comment]
Fix with commit fbc62b0.
